### ISSUE TITLE
Graf

### ISSUE THREAD

**Issue by Antoninecek** [Antoninecek/ProjektSTI#4]
Roztahnout graf, rozelit graf, smrsknout graf, proste graf.

**Comment by ondrejkomarek** [comment]
graf je slušnej, popsal bych osy jeste

**Comment by Minaj1k** [comment]
Když zavřu okno s grafem dřív, než se načte, tak to padne

**Comment by Antoninecek** [comment]
Se slzou v oku uzaviram toto issue.
